config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, :controllers => { registrations: "registrations" }
  resources :categories, only: %i(index show)

  namespace :admin do
    resources :categories
    resources :static_pages, only: %i(index)
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :word
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words

  validates :name, presence: true,
                   length: { maximum: Settings.validate.category.name.max_length },
                   uniqueness: { case_sensitive: false }

  scope :latest, -> { order(created_at: :desc) }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  has_many :lesson_words
  has_many :words, through: :lesson_words
end

app/models/lesson_word.rb
class LessonWord < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lessons
  has_many :active_relationships, foreign_key: "follower_id",
                                  class_name: Follow.name,
                                  dependent: :destroy
  has_many :passive_relationships, class_name:  Follow.name,
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum sex: [:male, :female]
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :answers
  has_many :lesson_words
  has_many :lessons, through: :lesson_words
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!

  layout "admin/application"
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :load_category, only: %i(edit update destroy)

  def index
    @categories = Category.latest.page(params[:page]).per Settings.pagination.category.admin
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params

    if @category.save
      flash[:success] = t ".success"
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t ".false"
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".success"
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t ".false"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".false"
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit :name
  end

  def load_category
    @category = Category.find params[:id]
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.latest.page(params[:page]).per Settings.pagination.category.user
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [:name, :email, :birthday, :sex, :avatar, :address, :password, :password_confirmation]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.slim
.row
  .col-md-12.col-md-offset-3
    = form_for([:admin, @category]) do |f|
      = render "shared/error_messages", object: f.object

      = f.label :name
      br/
      = f.text_field :name, autofocus: true, class: "form-control", autocomplete: "name"
      br/
      = f.submit yield(:button_text), class: "btn btn-primary"

app/views/admin/categories/edit.slim
- provide :button_text, t(".edit_categories")
center
  h1= t ".edit_categories"
  br/
  = render "form"

app/views/admin/categories/index.slim
center
  h1= t ".list_categories"
  br/
  = link_to t(".new_cat"), new_admin_category_path, class: "btn btn-primary"
  table#background_font.table.table-hover.table-secondary
    thead
      tr
        th = t ".serial"
        th = t ".category_name"
        th = t ".action_category"
    tbody
    - @categories.each_with_index do |category, index|
      tr
        td = index + Settings.pagination.category.admin * (@categories.current_page - 1) + 1
        td = category.name
        td
          = link_to t(".edit_cat"), edit_admin_category_path(category), class: "btn btn-info"
          = link_to t(".delete_cat"), admin_category_path(category), method: :delete, class: "btn btn-danger"

= paginate @categories

app/views/admin/categories/new.slim
- provide :button_text, t(".new_categories")
center
  h1= t ".new_categories"
  br/
  = render "form"

app/views/admin/static_pages/index.slim
hello admin

app/views/categories/index.slim
center
  h1= t ".list_categories"
  br/
  table#background_font.table.table-hover.table-secondary
    thead
      tr
        th = t ".serial"
        th = t ".category_name"
    tbody
    - @categories.each_with_index do |category, index|
      tr
        td = index + Settings.pagination.category.user * (@categories.current_page - 1) + 1
        td = category.name

= paginate @categories

app/views/layouts/_footer.slim
footer
  nav.navbar-nav.navbar-right
    .container
      .row
        .col-xl-4
          ul.nav.navbar-nav.navbar-left.list-group.list-group-horizontal
            li.list-group-item.border-0 = link_to t(".english"), locale: :en
            li.list-group-item.border-0 = link_to t(".vietnamese"), locale: :vi
        .col-xl-4
          .footer_mid
            = t ".copyright"
        .col-xl-4
          ul.footer_right.nav.navbar-nav.navbar-left.list-group.list-group-horizontal
            li.list-group-item.border-0 = link_to t(".about_us"), "#"
            li.list-group-item.border-0 = link_to t(".contact"), "#"

app/views/layouts/_header.slim
header
  nav.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to t(".e_learning"), root_path , id: "logo"
      nav
        ul.nav.navbar-nav.navbar-right.list-group.list-group-horizontal
          li.list-group-item.border-0 = link_to t(".home"), root_path
          li.list-group-item.border-0 = link_to t(".help"), "#"
          li.list-group-item.border-0 = link_to t(".category"), categories_path
          ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li.list-group-item.border-0 = link_to current_user.name, "#"
            li.list-group-item.border-0 = link_to t(".profile"), "#"
            - if current_user.admin? 
              li.list-group-item.border-0 = link_to t(".manage"), admin_static_pages_path
            li.divider
            li.list-group-item.border-0 = link_to t(".log_out"), destroy_user_session_path, method: :delete
          - else
            li.list-group-item.border-0 = link_to t(".log_in"), new_user_session_path

app/views/layouts/admin/_footer.slim
footer
  nav.navbar-nav.navbar-right
    .container
      .row
        .col-xl-4
          ul.nav.navbar-nav.navbar-left.list-group.list-group-horizontal
            li.list-group-item.border-0 = link_to t(".english"), locale: :en
            li.list-group-item.border-0 = link_to t(".vietnamese"), locale: :vi
        .col-xl-4
          .footer_mid
            = t ".copyright"
        .col-xl-4
          ul.footer_right.nav.navbar-nav.navbar-left.list-group.list-group-horizontal

app/views/layouts/admin/_header.slim
header
  nav.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to t(".e_learning"), root_path , id: "logo"
      nav
        ul.nav.navbar-nav.navbar-right.list-group.list-group-horizontal
          li.list-group-item.border-0 = link_to t(".home"), admin_static_pages_path
          li.list-group-item.border-0 = link_to t(".category"), admin_categories_path
          li.list-group-item.border-0 = link_to current_user.name, "#"
          li.list-group-item.border-0 = link_to t(".log_out"), destroy_user_session_path, method: :delete

app/views/layouts/admin/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title = t ".e_learning"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
    link href="/assets/favicon.ico" rel=("shortcut icon") type="image/x-icon" /
  body
    = render "layouts/admin/header"
    .container
      - flash.each do |message_type, message|
        div class=("alert alert-#{message_type}") = message
      = yield
    = render "layouts/admin/footer"

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title = t ".e_learning"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
    link href="/assets/favicon.ico" rel=("shortcut icon") type="image/x-icon" /
  body
    = render "layouts/header"
    .container
      - flash.each do |message_type, message|
        div class=("alert alert-#{message_type}") = message
      = yield
    = render "layouts/footer"

app/views/shared/_error_messages.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      = t "notice"
      = pluralize object.errors.count, "error"
      | \.
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/static_pages/home.slim
= t ".hello_word"